apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-mcauchy
  namespace: argocd
spec:
  project: default
  source:
    # GitLab self-hosted on VM2 (gitlab-vm)
    repoURL: http://192.168.56.10/root/iot-manifests.git
    targetRevision: main
    path: confs/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true