apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      label:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab:1.21.0
        ports:
        - containerPort: 3000
