# -*- mode: ruby -*-
# vi: set ft=ruby :

# Configuration variables
SERVER_NAME = "mcauchyS"
WORKER_NAME = "mcauchySW"
SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/jammy64" -> linux
  config.vm.box_check_update = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Shared folder for token exchange between server and worker
  config.vm.synced_folder "./shared", "/vagrant_shared", create: true

  # Server (Controller) configuration
  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP

    server.vm.provider "virtualbox" do |vb|
      vb.name = SERVER_NAME
      vb.memory = "1024"
      vb.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/install_k3s_server.sh", 
      env: {
        "SERVER_IP" => SERVER_IP
      }
    end
  end
  # ServerWorker (worker) configuration
  config.vm.define WORKER_NAME do |worker|
    worker.vm.hostname = WORKER_NAME
    worker.vm.network "private_network", ip: WORKER_IP

    worker.vm.provider "virtualbox" do |vb|
      vb.name = WORKER_NAME
      vb.memory = "1024"
      vb.cpus = 1
    end

    worker.vm.provision "shell", path: "scripts/install_k3s_worker.sh",
      env: {
        "SERVER_IP" => SERVER_IP
      }
  end
end
